[package]
name = "yt-to-mp3-4"
version = "0.1.0"
edition = "2024"

[dependencies]
arc = "0.0.1"
dirs = "6.0.0"
eframe = "0.31.1"
egui = "0.31.1"
filetime = "0.2.25"
num_cpus = "1.16.0"
open = "5.3.2"
rfd = "0.15.3"
rustube = "0.6.0"
sanitize-filename = "0.6.0"
tokio = "1.44.1"
