name: Daily Linux Build and Upload

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Download ffmpeg
      run: |
        mkdir -p bin/linux
        curl -L https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz -o ffmpeg.tar.xz
        tar -xf ffmpeg.tar.xz --strip-components=1 -C bin/linux
        chmod +x bin/linux/ffmpeg bin/linux/ffprobe

    - name: Download yt-dlp
      run: |
        curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o bin/linux/yt-dlp
        chmod +x bin/linux/yt-dlp

    - name: Build Project
      run: cargo build --release

    - name: Package Binaries
      run: |
        mkdir -p dist
        cp target/release/yt-to-mp3-4 bin/linux/
        tar -czf dist/yt-to-mp3-4-linux-x86.tar.gz -C bin/linux .

    - name: Upload to GitHub Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: https://uploads.github.com/repos/TegranGrigorian/yt-to-mp3-4/releases/${{ secrets.RELEASE_ID }}/assets{?name,label}
        asset_path: dist/yt-to-mp3-4-linux-x86.tar.gz
        asset_name: yt-to-mp3-4-linux-x86.tar.gz
        asset_content_type: application/gzip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}